apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "netbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "netbox.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "netbox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "netbox.fullname" . }}
                  key: secretKey
            - name: DB_NAME
              value: {{ .Values.database.name }}
            - name: DB_USER
              value: {{ .Values.database.user }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "netbox.fullname" . }}
                  key: dbPassword
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "netbox.fullname" . }}
                  key: dbHost
            - name: DB_PORT
              value: {{ .Values.database.port }}
            - name: REDIS_DATABASE
              value: {{ .Values.redisHooks.database | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redisHooks.port | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "netbox.fullname" . }}
                  key: redisHooksPassword
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "netbox.fullname" . }}
                  key: redisHooksHost
            - name: REDIS_TIMEOUT
              value: {{ .Values.redisHooks.timeout | quote }}
            - name: REDIS_SSL
              value: {{ .Values.redisHooks.ssl }}
            - name: REDIS_CACHE_DATABASE
              value: {{ .Values.redisCaching.database | quote }}
            - name: REDIS_CACHE_PORT
              value: {{ .Values.redisCaching.port | quote }}
            - name: REDIS_CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "netbox.fullname" . }}
                  key: redisCachingPassword
            - name: REDIS_CACHE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "netbox.fullname" . }}
                  key: redisCachingHost
            - name: REDIS_CACHE_TIMEOUT
              value: {{ .Values.redisCaching.timeout | quote }}
            - name: REDIS_CACHE_SSL
              value: {{ .Values.redisCaching.ssl }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
